### ISSUE TITLE
Retrieving the User data of an unranked player throws a TypeError

### ISSUE THREAD

**Issue by spreadnuts** [circleguard/ossapi#28]
The code:
`api.user(7433533)`
where the ID can be any unranked player, throws this error:
`TypeError: expected type <class 'int'> for value None, got type <class 'NoneType'> (for attribute: global_rank)`

**Comment by tybug** [comment]
Can you update ossapi to the latest version? This should have been fixed in v2.0.0beta8

**Comment by spreadnuts** [comment]
oops! fixed.
