### ISSUE TITLE
AttributeError: 'Search' object has no attribute 'user'

### ISSUE THREAD

**Issue by sortedcord** [circleguard/ossapi#40]
Installed ossapi the way it was mentioned in the readme and got the required credentials.

```py
from ossapi import *

api = OssapiV2(foo, bar, uri)
print(api.search(query="peppy").user.data[0].profile_colour)
```
Outputs an AttributeError that search does not have an attribute with the name 'user'

**Comment by tybug** [comment]
I renamed `Search.user` to `Search.users` and forgot to update the docs, use `api.search(query="peppy").users.data[0].profile_colour` instead
