### ISSUE TITLE
GameMode.CTB Returning STD

### ISSUE THREAD

**Issue by Eliminate247** [circleguard/ossapi#56]
When trying to gather a user's top plays in CTB, I receive their top std plays instead.
```
top = api.user_scores(userid, "best", GameMode.CTB, limit=50)
print(top)

> returns std scores
```

I have tried using `GameMode.CTB`, `GameMode.CATCH`, `mode="ctb"` and `mode="Catch"` (oddly enough I get `'catch' is not a valid GameMode` when all lowercase), all returning the same thing. Changing the gamemode works for all other modes except ctb.

**Comment by tybug** [comment]
the third parameter to `user_scores` is `include_fails: bool`, so passing a gamemode as the third positional parameter is treating it as the `include_fails` parameter and defaulting the request to std. You should be using `mode=GameMode.CATCH` (`GameMode.CTB` is deprecated) or `mode="fruits"` (don't blame me for the naming, blame the api).

**Comment by Eliminate247** [comment]
Haha you're kidding me. Spent a while trying to figure this one out. Not sure whether I'm the silly goose or the api for being called "fruits". Thanks for the quick response!
