### ISSUE TITLE
user scores returns empty list for recent

### ISSUE THREAD

**Issue by whois-hoeless** [circleguard/ossapi#64]
Running the ossapi trying to get the most recent score sometimes returns an empty list. Does the api get the most recent game in 18 hours or does it get the most recent game in general? Because I am unsure if it doesn't work because I didn't play in the last 24 hours or if it just doesn't work all the time for some other reason

**Comment by tybug** [comment]
This is expected. The recent scores endpoint only returns the most recent scores in the last 24 hours. If a user has not played in a day, their recent scores will be empty.

Another way to think about it is you are retrieving the same scores that are on the "recent scores" section of your profile. If there are no scores there, the api won't return any either.

**Comment by whois-hoeless** [comment]
I already thought that was the case but I wanted to make sure, thanks for the answer
