### ISSUE TITLE
`tournament_ban` is not a valid UserAccountHistoryType

### ISSUE THREAD

**Issue by yanda-dy** [circleguard/ossapi#69]
(Minor issue, [doesn't seem to be documented](https://osu.ppy.sh/docs/index.html#usercompact-useraccounthistory))

Replication:
```py
user = api.user(9997093)
```
Response:
```
ValueError: 'tournament_ban' is not a valid UserAccountHistoryType
```

**Comment by tybug** [comment]
fixed in v3.3.3 (by https://github.com/circleguard/ossapi/compare/dec24d7b6b5be0...437f2108129f), thanks
