### ISSUE TITLE
Some beatmap()/beatmap_attributes() variables are returned as int instead of float

### ISSUE THREAD

**Issue by 04nada** [circleguard/ossapi#70]
When `beatmap()` or `beatmap_attributes()` is called, whenever a `Beatmap` or `BeatmapDifficultyAttributes` instance has integral values for some of its variables (CS, AR, OD, HP, BPM) (e.g. `CS 4`/`AR 9`/`OD 8`/`HP 5`/`180 BPM`), those values get returned as `int` instead of `float`, despite the annotation saying that the return type should always be `float`.

I believe this might also apply to all of the `_difficulty` variables for `beatmap_attributes()` whenever the actual value is 0, such as `flashlight_difficulty` when `FL` isn't actually passed as a mod.

**Comment by tybug** [comment]
closed by dafa936592372394bc2d28d38452fcea8c567aa3
