### ISSUE TITLE
`beatmap_user_scores` returns generic list of `Score` instead of `BeatmapUserScore`

### ISSUE THREAD

**Issue by ItsMestro** [circleguard/ossapi#73]
Idk whether the type hint is just wrong or if the return type is meant to be different but using `beatmap_user_scores()` returns a `List[Score]` instead of the stated `List[BeatmapUserScore]` and breaking type hints.

**Comment by tybug** [comment]
Thanks for the report! The type hint is wrong here; it should be `List[Score]`.

That said, I'm not sure why the osu api returns a `Score` for that endpoint instead of a `BeatmapUserScore`. The latter makes more sense to me. Regardless, I've fixed the type hint for the next release.
